language: node_js
sudo: required

node_js:
  - "4.4.0"

addons:
  hosts:
    - api.openweathermap.org

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y socat
  - cat /etc/hosts
  - wget http://ipinfo.io/ip -qO -
  - npm install -g bower
  - npm install -g karma
  - npm install -g karma-cli
  - npm install -g protractor
  - npm install -g grunt
  - npm install -g grunt-cli
  - bower install
  - sudo socat TCP-LISTEN:80,fork TCP:${RTCP_HOST}:${RTCP_PORT} > /tmp/socat.log 2>&1 &
  - webdriver-manager start > /tmp/webdriver-manager.log 2>&1 &
  - scripts/web-server.js > /tmp/web-server.js.log 2>&1 &

script:
  - karma start config/karma.conf.js --single-run
  - grunt

after_script:
  - grunt makeReport
