language: node_js
node_js:
  - "4.4.0"

before_script:
  - npm install -g bower
  - npm install -g karma
  - npm install -g karma-cli
  - bower install

script:
  - karma start config/karma.conf.js --single-run
  - karma start config/karma-e2e.conf.js

